spring.data.mongodb.uri=mongodb+srv://barriossaltarinj_db_user:C1aiDNWL4dAt9Eem@cluster0.uteazdc.mongodb.net/kitchenmanager?appName=Cluster0
spring.data.mongodb.database=restaurante
server.port=8080

logging.level.org.springframework.security=TRACE
logging.level.com.example.demo=DEBUG

cloudinary.cloud-name=dpb7hg85q
cloudinary.api-key=528767535148873
cloudinary.api-secret=MvVJRMn-kVnPiIkmoyQJDvPjjJw

# Para ver las consultas a MongoDB
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG